from . import popular_today
from . import popular_films
from . import popular_serials
from . import popular_cartoons
from . import awaits_api
from . import new_films_api
from . import new_serials_api
from . import new_cartoons_api
from . import random_films_api
from . import random_serial_api
from . import random_cartoons_api
from . import create_url_api
from . import search_movie_api
from . import search_person_api
